POST http://localhost:8081/users/user/login
Content-Type: application/json

{
    "username": "ceo123",
    "password": "ceo12"
}
### Add Inventory Item

POST http://localhost:8081/inventory/addInventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQ1ODQ5MTUsImV4cCI6MTc2NTE4OTcxNX0.WOaPAE3FRt65_-CJa2RBmUwSlR3UWH2Jm9gLLoosG1w

{
    "itemName": "Test Item",
    "brand": "Test Brand",
    "code": "TIwads3432",
    "costUnit": 80,
    "sellingPrice": 100,
    "category": "Test Category",
    "quantity": 50,
    "expiryDate": "2025-12-31",
    "logo": "Users/users/Pictures/hehe.jpg"
}



### Get All Inventory Items
GET http://localhost:8081/inventory/getInventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQxOTg4MDcsImV4cCI6MTc2NDgwMzYwN30.eIDoS9KIxaIPcqpwkvv9uy-6sw9c73S-JIvALt39djw


### Delete Inventory Item
DELETE http://localhost:8081/inventory/deleteInventory/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQxOTg4MDcsImV4cCI6MTc2NDgwMzYwN30.eIDoS9KIxaIPcqpwkvv9uy-6sw9c73S-JIvALt39djw

### update Inventory Item
PUT http://localhost:8081/inventory/updateInventory/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQxOTg4MDcsImV4cCI6MTc2NDgwMzYwN30.eIDoS9KIxaIPcqpwkvv9uy-6sw9c73S-JIvALt39djw
Content-Type: application/json

{
    "itemName": "Updatedasd Item",
    "brand": "Updated Brand",
    "code": "UI123",
    "price": 150,
    "category": "Updated Category",
    "quantity": 75
}


### Get All Purchases
GET http://localhost:8081/inventory/Purchases/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQ4NDE1MjUsImV4cCI6MTc2NTQ0NjMyNX0.qT-PwyImZcQDJABcLRyPgqF5a4BbpsuZPoN1bjbjarY
Content-Type: application/json

### Addd Purchase Record
POST http://localhost:8081/inventory/addInventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQ4NDE1MjUsImV4cCI6MTc2NTQ0NjMyNX0.qT-PwyImZcQDJABcLRyPgqF5a4BbpsuZPoN1bjbjarY
Content-Type: multipart/form-data; boundary=WebKitFormBoundary123

--WebKitFormBoundary123
Content-Disposition: form-data; name="itemName"

Body Lotion
--WebKitFormBoundary123
Content-Disposition: form-data; name="brand"

SmoothSkin
--WebKitFormBoundary123
Content-Disposition: form-data; name="code"

BL-505
--WebKitFormBoundary123
Content-Disposition: form-data; name="costUnit"

200
--WebKitFormBoundary123
Content-Disposition: form-data; name="sellingPrice"

300
--WebKitFormBoundary123
Content-Disposition: form-data; name="reference"

PUR-BL505
--WebKitFormBoundary123
Content-Disposition: form-data; name="suppliers"

BeautyMart
--WebKitFormBoundary123
Content-Disposition: form-data; name="quantity"

45
--WebKitFormBoundary123
Content-Disposition: form-data; name="grandTotal"

9000
--WebKitFormBoundary123
Content-Disposition: form-data; name="expiryDate"

2027-09-10
--WebKitFormBoundary123
Content-Disposition: form-data; name="category"

Product
--WebKitFormBoundary123
Content-Disposition: form-data; name="logo"; filename="body_lotion.jpg"
Content-Type: image/jpeg

@./body_lotion.jpg
--WebKitFormBoundary123--