POST http://localhost:8081/users/user/login
Content-Type: application/json

{
    "username": "ceo123",
    "password": "ceo12"
}
### Add Inventory Item

POST http://localhost:8081/inventory/addInventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQ0MDk3MTMsImV4cCI6MTc2NTAxNDUxM30.gByvktVa4vcd0E5h129WNwVWFvylWvSCaNQboVVG5jg
Content-Type: application/json

{
    "itemName": "Test Item",
    "brand": "Test Brand",
    "code": "TIwad3432",
    "costUnit": 80,
    "sellingPrice": 100,
    "category": "Test Category",
    "quantity": 50,
    "expiryDate": "2025-12-31",
    "logo": null
}



### Get All Inventory Items
GET http://localhost:8081/inventory/getInventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQxOTg4MDcsImV4cCI6MTc2NDgwMzYwN30.eIDoS9KIxaIPcqpwkvv9uy-6sw9c73S-JIvALt39djw


### Delete Inventory Item
DELETE http://localhost:8081/inventory/deleteInventory/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQxOTg4MDcsImV4cCI6MTc2NDgwMzYwN30.eIDoS9KIxaIPcqpwkvv9uy-6sw9c73S-JIvALt39djw

### update Inventory Item
PUT http://localhost:8081/inventory/updateInventory/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImFkbWluIiwidXNlcm5hbWUiOiJjZW8xMjMiLCJpYXQiOjE3NjQxOTg4MDcsImV4cCI6MTc2NDgwMzYwN30.eIDoS9KIxaIPcqpwkvv9uy-6sw9c73S-JIvALt39djw
Content-Type: application/json

{
    "itemName": "Updatedasd Item",
    "brand": "Updated Brand",
    "code": "UI123",
    "price": 150,
    "category": "Updated Category",
    "quantity": 75
}
